# Generated by Django 5.1.3 on 2024-11-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
